name: Demo Workflow
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-22.04
    steps:
      - name: Print to console
        run: echo Hello Actions
      - name: Print two
        run: |
          echo First line
          echo Secondl iine
