name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy
        run: |
          ssh root@194.135.105.154
          ${{ secrets.DEPLOY_SECRET }}
          pm2 stop index.ts
          git fetch
          git pull origin main
          pm2 start index.ts
          echo Success
          
