name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SECRET_RSA_DEPLOY }}
      # - name: NVM Setup Node
      #   uses: irby/setup-node-nvm@master
      #   with:
      #     node-version: lts/*
      # - name: Check
      #   run: |
      #     node -v
      #     npm -v
      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no root@194.135.105.154 << 'EOF'
            cd tg-app-node/
            pkill node
            npm run stop
            git fetch
            git pull origin main
            git checkout origin/main
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
            source ~/.bashrc
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            nvm install node
            nvm install-latest-npm
            node -v
            nvm --version
            npm ci
            nohup npm run tsnode &
          EOF
