name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SECRET_RSA_DEPLOY }}
      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no root@194.135.105.154 << 'EOF'
            cd tg-app-node/
            git fetch
            git pull origin main
            npm ci
            pm2 restart index.ts
          EOF
